displayName: LDAP Authentication Plugin
type: middleware

import: github.com/wiltonsr/ldapauth

summary: 'An open source Traefik Middleware that enables Authentication via LDAP in a similar way to Traefik Enterprise'

testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
