[http.middlewares]
[http.middlewares.my-ldapAuth.plugin.ldapAuth]
Attribute = "uid"
BaseDN = "dc=example,dc=com"
Enabled = "true"
LogLevel = "DEBUG"
Port = "389"
Url = "ldap://ldap.forumsys.com"
AllowedGroups = ["ou=mathematicians,dc=example,dc=com","ou=italians,ou=scientists,dc=example,dc=com"]
AllowedUsers = ["euler", "uid=euclid,dc=example,dc=com"]
# SearchFilter must escape curly braces when using toml file
# https://toml.io/en/v1.0.0#string
# SearchFilter = '''(\{\{.Attribute\}\}=\{\{.Username\}\})'''
